### PR TITLE
Implement ASGI server

### LINKED ISSUE #37: ASGI compatible server
This would be more useful if the server were compatible with the [ASGI spec](https://asgi.readthedocs.io/en/latest/). If it were, ypy-websocket could immediately be used in conjunction with popular web servers like [Starlette](https://www.starlette.io/), [FastAPI](https://fastapi.tiangolo.com/), and [Sanic](https://sanic.readthedocs.io/en/stable/).

### PR DESCRIPTION
**Pull request by davidbrochart**
Closes #37

### CODE REVIEW

**Comment by ToniRV** [comment]
@davidbrochart, how would you use this with FastAPI as the ASGI server?

**Comment by davidbrochart** [comment]
I am in vacation and have limited access to the Internet, but I'll try to answer your question soon.
Don't hesitate to ping me in case I don't get back to you, say in two weeks.

**Comment by ToniRV** [comment]
Hi @davidbrochart, no worries, I found my way, somehow 😅 

By the way, I'm trying to build a `ypy-mongodb`, looking at your implementation of `ystore` for `sqllitedb`.
I could follow your approach there and do the same with `pymongo`, right?

That said, any help would be super welcome since I'm reverse engineering stuff and have little knowledge of Yjs or Ypy.
I'll ping you if I have more questions (is there a better way to reach out?), want to respect your vacation time as well.

**Comment by davidbrochart** [comment]
> I could follow your approach there and do the same with `pymongo`, right?

Yes, actually I think the Y stores should not depend on `ypy-websocket` (see #19), as they could be used in other contexts.
But yes you could look at the [SQLiteYStore](https://github.com/y-crdt/ypy-websocket/blob/1af218b034ac16d1bd20d53230e83c9570a799be/ypy_websocket/ystore.py#L285) to implement a Y store for MongoDB.
I should add more documentation, but feel free to ask for help, maybe on a new issue.

**Pull request merged**
