### PR TITLE
Migrate to `hatch`

### PR DESCRIPTION
**Pull request by jtpio**
Following the current trend of migrating python projects to `hatch`.

Done with: `hatch new --init`

### CODE REVIEW

**Comment by davidbrochart** [comment]
Not sure if the flake8's `max-line-length = 100` was taken into account?

**Comment by jtpio** [comment]
Not sure, seems to be passing now with https://github.com/y-crdt/ypy-websocket/pull/36/commits/8cdb7a7268253662ea15195ccda43e55b465abc0.

**Comment by davidbrochart** [comment]
Yes, or maybe we don't have such lines anyway.

**Comment by davidbrochart** [comment]
Thanks!

**Comment by ofek** [comment]
Nice! fyi flake8 doesn't support that yet https://github.com/PyCQA/flake8/issues/234

**Pull request merged**
